//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tests.test_files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tests.test_files.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6
        ///aaabbb
        ///ab
        ///abc
        ///mnop
        ///xyyx
        ///xaxbbbxx.
        /// </summary>
        internal static string anagram1 {
            get {
                return ResourceManager.GetString("anagram1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3
        ///1
        ///-1
        ///2
        ///0
        ///1.
        /// </summary>
        internal static string anagram1_res {
            get {
                return ResourceManager.GetString("anagram1_res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000
        ///24 oz
        ///36 xr
        ///43 cu
        ///44 oq
        ///55 qf
        ///2 oz
        ///96 bk
        ///1 tv
        ///2 jy
        ///27 wy
        ///30 kj
        ///11 mn
        ///85 mp
        ///3 wu
        ///54 zq
        ///80 ee
        ///29 rv
        ///46 wi
        ///13 zu
        ///37 rv
        ///29 sc
        ///59 on
        ///76 ts
        ///86 wf
        ///49 gg
        ///9 yc
        ///2 gr
        ///46 ny
        ///56 ws
        ///15 jr
        ///74 lc
        ///50 ag
        ///77 vk
        ///16 er
        ///84 cf
        ///82 dn
        ///12 ss
        ///4 pe
        ///35 pm
        ///28 qo
        ///47 ym
        ///54 lr
        ///34 bx
        ///18 jm
        ///20 kn
        ///86 av
        ///17 rx
        ///35 zb
        ///14 il
        ///10 zo
        ///43 lk
        ///58 fk
        ///0 xs
        ///91 cn
        ///4 qq
        ///95 fw
        ///75 eo
        ///83 pr
        ///65 tc
        ///11 vd
        ///32 kr
        ///55 so
        ///24 dk
        ///51 br
        ///38 db
        ///19 sr
        ///91 ir
        ///76 fe
        ///60 hr
        ///0 jz
        ///44 ju
        ///26 td
        ///70 ki
        ///62 zd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string countsort3_file1 {
            get {
                return ResourceManager.GetString("countsort3_file1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3
        ///abcdde
        ///baccd
        ///eeabg.
        /// </summary>
        internal static string gemstones1 {
            get {
                return ResourceManager.GetString("gemstones1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 3
        ///2 5 6.
        /// </summary>
        internal static string greedyflorist1 {
            get {
                return ResourceManager.GetString("greedyflorist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 2
        ///2 5 6.
        /// </summary>
        internal static string greedyflorist2 {
            get {
                return ResourceManager.GetString("greedyflorist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 3
        ///390225 426456 688267 800389 990107 439248 240638 15991 874479 568754 729927 980985 132244 488186 5037 721765 251885 28458 23710 281490 30935 897665 768945 337228 533277 959855 927447 941485 24242 684459 312855 716170 512600 608266 779912 950103 211756 665028 642996 262173 789020 932421 390745 433434 350262 463568 668809 305781 815771 550800.
        /// </summary>
        internal static string greedyflorist3 {
            get {
                return ResourceManager.GetString("greedyflorist3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2
        ///10 10
        ///7283455864
        ///6731158619
        ///8988242643
        ///3830589324
        ///2229505813
        ///5633845374
        ///6473530293
        ///7053106601
        ///0834282956
        ///4607924137
        ///3 4
        ///9505
        ///3845
        ///3530
        ///15 15
        ///400453592126560
        ///114213133098692
        ///474386082879648
        ///522356951189169
        ///887109450487496
        ///252802633388782
        ///502771484966748
        ///075975207693780
        ///511799789562806
        ///404007454272504
        ///549043809916080
        ///962410809534811
        ///445893523733475
        ///768705303214174
        ///650629270887160
        ///2 2
        ///99
        ///99.
        /// </summary>
        internal static string gridsearch_1 {
            get {
                return ResourceManager.GetString("gridsearch_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3
        ///1000 1000
        ///649878239947538712104652760661359717721422234065538127372846076655249287574475716060021711685834809241321369159172869454317166001033938679176047500576795636691518483947335700864218097686657510618643901857509759971436621125124207338390011105253171917452252131161900913418799500647106549214151582980202861196137958887987268711020167935425109277372669073806216864899187648169893700712055836583834953552127410338977839561590767095462003494768570707196394509071395279799396038019047097472226141022882639 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gridsearch_2 {
            get {
                return ResourceManager.GetString("gridsearch_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///1000 1000
        ///947197362656799531118104673519015509020023213996909759644753569428029174174739304686276823097593343238523807171774498086680402742951469271944991201355509703365671840775308151258197411063893182769220939354677820545622039755227498085412240076218899654470372419581467041672099612852343688538105570284120626946741553137675700504464789631027965654392265119476204119593519669211680464516719547651492855081766782645021461768863969333386890858944813379477831873681350743723301861243093148776152510460257892 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gridsearch_3 {
            get {
                return ResourceManager.GetString("gridsearch_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///4 6
        ///123412
        ///561212
        ///123634
        ///781288
        ///2 2
        ///12
        ///34.
        /// </summary>
        internal static string gridsearch_4 {
            get {
                return ResourceManager.GetString("gridsearch_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///2 6
        ///999999
        ///121211
        ///2 2
        ///99
        ///11.
        /// </summary>
        internal static string gridsearch_5 {
            get {
                return ResourceManager.GetString("gridsearch_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8
        ///7 2 1 4 5 1 3 3.
        /// </summary>
        internal static string lrect0 {
            get {
                return ResourceManager.GetString("lrect0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///8979 4570 6436 5083 7780 3269 5400 7579 2324 2116.
        /// </summary>
        internal static string lrect1 {
            get {
                return ResourceManager.GetString("lrect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000
        ///17251 111021 468274 103217 350415 61669 796450 156297 953054 440459 2535 286823 298241 387365 223650 332004 425095 26510 469625 680912 818738 228517 300529 890259 761985 471457 634320 720004 819617 52746 124428 836868 163767 109054 456437 30534 170723 252887 186832 123778 209698 705719 410601 507940 609436 150603 356296 550883 177113 825921 231795 512203 570790 48677 402462 332776 520134 553135 569132 339751 605881 209912 692971 286001 318967 149408 316535 489690 918647 19719 129820 128346 241790 567 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lrect2 {
            get {
                return ResourceManager.GetString("lrect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 4 1
        ///1 2 3 4
        ///5 6 7 8
        ///9 10 11 12
        ///13 14 15 16.
        /// </summary>
        internal static string matrixrotation_1 {
            get {
                return ResourceManager.GetString("matrixrotation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 3 4 8
        ///1 7 11 12
        ///5 6 10 16
        ///9 13 14 15.
        /// </summary>
        internal static string matrixrotation_11 {
            get {
                return ResourceManager.GetString("matrixrotation_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 4 2
        ///1 2 3 4
        ///5 6 7 8
        ///9 10 11 12
        ///13 14 15 16.
        /// </summary>
        internal static string matrixrotation_2 {
            get {
                return ResourceManager.GetString("matrixrotation_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 4 8 12
        ///2 11 10 16
        ///1 7 6 15
        ///5 9 13 14.
        /// </summary>
        internal static string matrixrotation_21 {
            get {
                return ResourceManager.GetString("matrixrotation_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 8 40
        ///9718805 60013003 5103628 85388216 21884498 38021292 73470430 31785927
        ///69999937 71783860 10329789 96382322 71055337 30247265 96087879 93754371
        ///79943507 75398396 38446081 34699742 1408833 51189 17741775 53195748
        ///79354991 26629304 86523163 67042516 54688734 54630910 6967117 90198864
        ///84146680 27762534 6331115 5932542 29446517 15654690 92837327 91644840
        ///58623600 69622764 2218936 58592832 49558405 17112485 38615864 32720798
        ///49469904 5270000 32589026 56425665 23544383 90502426 63729346 35319547
        ///208 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string matrixrotation_3 {
            get {
                return ResourceManager.GetString("matrixrotation_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 93754371 53195748 90198864 91644840 32720798 35319547 89653362 50410021
        ///31785927 25289229 10844931 97945481 5270000 69622764 27762534 43779176
        ///73470430 90786953 42430633 96642353 88915819 85669747 26629304 86544343
        ///38021292 22590518 90502426 67042516 54688734 32589026 75398396 61983443
        ///21884498 54702481 17112485 5932542 29446517 2218936 71783860 7071172
        ///85388216 71197978 15654690 58592832 49558405 6331115 10329789 56239301
        ///5103628 47265349 54630910 56425665 23544383 86523163 96382322 27353496
        ///6001300 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string matrixrotation_31 {
            get {
                return ResourceManager.GetString("matrixrotation_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7
        ///3
        ///10
        ///100
        ///300
        ///200
        ///1000
        ///20
        ///30.
        /// </summary>
        internal static string maxmin1 {
            get {
                return ResourceManager.GetString("maxmin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///4
        ///1
        ///2
        ///3
        ///4
        ///10
        ///20
        ///30
        ///40
        ///100
        ///200.
        /// </summary>
        internal static string maxmin2 {
            get {
                return ResourceManager.GetString("maxmin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6
        ///3
        ///10
        ///20
        ///30
        ///100
        ///101
        ///102.
        /// </summary>
        internal static string maxmin3 {
            get {
                return ResourceManager.GetString("maxmin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100000
        ///10000
        ///58457907
        ///37850775
        ///19743393
        ///70718573
        ///34395679
        ///32448076
        ///48664348
        ///12492248
        ///77695616
        ///66342676
        ///38120300
        ///9282025
        ///55261855
        ///43659379
        ///33441482
        ///86981291
        ///40931037
        ///88952744
        ///35901370
        ///31515991
        ///40415448
        ///74074048
        ///5489528
        ///3530527
        ///67783448
        ///62643927
        ///62071533
        ///87401372
        ///76977624
        ///5297084
        ///56307794
        ///35435531
        ///95664211
        ///76051187
        ///58670457
        ///30059891
        ///8499264
        ///7334805
        ///42552139
        ///38711232
        ///26193833
        ///80672439
        ///47993257
        ///81455689
        ///24331818
        ///33951091
        ///20953332
        ///17779207
        ///22903835
        ///56854702
        ///181 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maxmin4 {
            get {
                return ResourceManager.GetString("maxmin4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 2  
        ///1 5 3 4 2  .
        /// </summary>
        internal static string pairs1 {
            get {
                return ResourceManager.GetString("pairs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3  
        ///cab  
        ///bcab  
        ///ccccc.
        /// </summary>
        internal static string stringreduction1 {
            get {
                return ResourceManager.GetString("stringreduction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2
        ///1
        ///5.
        /// </summary>
        internal static string stringreduction11 {
            get {
                return ResourceManager.GetString("stringreduction11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100
        ///baccbbacababacacbaccaacccbccaccbabac
        ///acaacababbcbabbbbbaaaabacaabbcbac
        ///bcbcacacbbaaccbaacbccaca
        ///ccbaccbcabcabcbacbaaabbacaaabaabbabacaabbcbabacbcccbaabacccaacbbaacabcbacabb
        ///aaba
        ///cbbbcabbbababcababbccbcacbbaacbaacbcabbbbbbabcbbbbaacaabbcacbbccabcaaccbaabbab
        ///bcbccbcbbababcaaacbbcaab
        ///bacbccacacbbabaacbbacaacbcbbcaccabaaaccabcccaacccccbcbbaaacaabcbcbb
        ///acaccaccabcaaacababcaacaccacbccbbababaacaabbaaccbbbccabcababacaabcbaacaacbcacccbbaabacbcabacbcccbaa
        ///cbaccaccacabccabbbaaabcbbccccccaacababaaacbbcbcb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stringreduction2 {
            get {
                return ResourceManager.GetString("stringreduction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///1
        ///2
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///2
        ///1
        ///1
        ///1
        ///2
        ///2
        ///1
        ///1
        ///2
        ///2
        ///1
        ///2
        ///1
        ///2
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///2
        ///2
        ///1
        ///1
        ///2
        ///2
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///2
        ///2
        ///1
        ///1
        ///1
        ///2
        ///1
        ///1
        ///1
        ///1
        ///2
        ///2
        ///1
        ///2
        ///1
        ///2
        ///1
        ///1
        ///1
        ///2
        ///1
        ///1
        ///2
        ///1
        ///2
        ///1
        ///1
        ///2
        ///1
        ///2
        ///1
        ///1
        ///1
        ///1
        ///1
        ///2
        ///1
        ///2
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///2
        ///1
        ///1
        ///2
        ///1.
        /// </summary>
        internal static string stringreduction22 {
            get {
                return ResourceManager.GetString("stringreduction22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ibfdgaeadiaefgbhbdghhhbgdfgeiccbiehhfcggchgghadhdhagfbahhddgghbdehidbibaeaagaeeigffcebfbaieggabcfbiiedcabfihchdfabifahcbhagccbdfifhghcadfiadeeaheeddddiecaicbgigccageicehfdhdgafaddhffadigfhhcaedcedecafeacbdacgfgfeeibgaiffdehigebhhehiaahfidibccdcdagifgaihacihadecgifihbebffebdfbchbgigeccahgihbcbcaggebaaafgfedbfgagfediddghdgbgehhhifhgcedechahidcbchebheihaadbbbiaiccededchdagfhccfdefigfibifabeiaccghcegfbcghaefifbachebaacbhbfgfddeceababbacgffbagidebeadfihaefefegbghgddbbgddeehgfbhafbccidebgehifafgbghafacgfdccgifdcb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string validstring1 {
            get {
                return ResourceManager.GetString("validstring1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ebhcgicceggecgdcibbeicigehhebabiehbdgaeaigihghbhigihfebgabicbgfhhedgbfehiahchcecedffhccebifcbdfcfaecicafahfiecceeaabbecfhgbfifabbffadcieeaiidddhfdeccaedbgcfdehbadihheieidgcfbdiiicgahebfbbdfeffegbdhgdagefhbgafaabfghdcbfdhabhfahbdhgifbghhafcieachcbeabccbiigdcfegcccfafehegbiecbdhabcffggiifaabfagbfdfbfacdcafabccgibiidgabiabigbgbbaideeagaaffcddhieicehhchfedfgbgbfhgedhacegaieeedggacbbgadeibbbcdhbabbieibcfbhgdbbiecdhbffaghhchhddcihgdgbgdcfgfggeaahffgiddeadgcegaiddhhdgagdidgacafececiebeigcbdfaedibbgbhciihcdifbacdag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string validstring2 {
            get {
                return ResourceManager.GetString("validstring2", resourceCulture);
            }
        }
    }
}
